apiVersion: v1
kind: Service
metadata:
  name: condor-pagos
  labels:
    app.kubernetes.io/name: pagos
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
spec:
  selector:
    app: condor-pagos
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  type: LoadBalancer
